#!/bin/sh

regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo Your email $email satisfied Git policy
    exit 0

else
    echo Your email $email doesnt satisfy Git policy
    exit 1
fi